[make] Use haxelib git to install hxcpp
Installing from lib.haxe.org via ssl causes problems.

On Mac, it downloads incorrectly whenever the `--quiet` flag is used.

On Windows, it gives the error:
```
Error: Failed with error: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
```